### PR TITLE
Add client support for permissions management

### PR DESCRIPTION
**Pull request by laurahlark**
Dependent on server support being checked in (https://bitbucket.org/b612astrogators/exp1/pull-requests/30/ser-3-expose-permission-management-through/diff). Server support is running in dev, though, and this all works as-is (will flip flag to use prod before checking in).

### CODE REVIEW

**Comment by laurahlark** [comment]
Users need to manipulate permissions to the projects they own - the admin
of a project (e.g. someone in the LSST group) should give access to others
on their team to run propagations, etc.

**Comment by samotiwala** [comment]
Ahh I see, just projects they own and not permissions in general. Gotcha. LGTM!

**Comment by laurahlark** [comment]
Yup, and permissions changes will be authorized just like all others - so for example, you're only allowed to give someone READ permission on an object if you have GRANT_READ permission on that object (which you have if you have ADMIN permission). Updated small changes to accommodate change on server-side CL. I'll merge once server side is pushed to prod, shortly.

**Comment by samotiwala** [comment]
Cool, I like it!

**Comment by laurahlark** [comment]
Pushed to prod, tests pass, merging.

**Pull request merged**
