### PR TITLE
Refactor batch/batches objects and modules.

### PR DESCRIPTION
**Pull request by laurahlark**
Also adds a module for STM propagations.

Basically, I realized while trying to hook stuff up to Vivek's STM propagating code that the modules and objects I'd made weren't as usable as I'd like. This is a very large refactoring that I hope makes batches very easy to work with. This includes:

- separating data from process for batches (this is all in batch2)
- refactoring Batch to use new objects, but leaving Batch for backwards-compatibility (we can discuss to what extent we want to do this)
- BatchRunner is now BatchRunManager, and manages the state of a specific set of batch runs, rather than being a long-lived module like Batches or Projects.

I'd love to talk to you about this and get your feedback on the structure and usability. Maybe we could set up a hangout in the next couple days (maybe before or after the meeting Friday?)? If you think it's a good setup, I'd like to try and get this in before the hackathon so that we can use it there.

### CODE REVIEW

**Comment by samotiwala** [comment]
Something else I'd like to do, since we are refactoring, is move the authentication stuff out of test.py to somewhere else...that script was meant to be an example to the user who wants to make a run and I'm not really sure it belongs there.

**Comment by laurahlark** [comment]
OK! When are you free for a tour? Maybe this afternoon/evening your time? I'd like to get this in for the hackathon if possible.

Regarding Batch2, the naming is dependent on what we want to do with Batch. What I'd really love to do is rename Batch to DeprecatedBatch, Batch2 to BatchPropagation or something, and implement Batch to just print a warning and instructions for how to use either BatchPropagation or DeprecatedBatch and exit. Then at the hackathon we can help everybody migrate. We shouldn't have both Batch and Batch2 in the long run.

**Comment by laurahlark** [comment]
(updated with Tatiana's suggestions)

**Comment by samotiwala** [comment]
Sounds good. Does Monday work? I plan to work all day Monday.

**Comment by laurahlark** [comment]
How about Monday early evening your time? I should be home by 8, 8:30. I’m
not working today and am in Pennsylvania right now but will do a bit of
code review answering when I get home.

**Comment by samotiwala** [comment]
Yes, let's do that!

**Comment by laurahlark** [comment]
Hey, it’s looking like it’s going to be later than that, 9 at least. Can I
email you when I get home?

**Comment by laurahlark** [comment]
Sweet, thanks for reviewing. Necessary server-side support is pushed to prod, integration tests have switched to use prod so this is ready to merge. I'm going to give it a last once-over in the morning before submitting, then get on the migration and demos.

**Comment by laurahlark** [comment]
All tests and scripts run successfully. Merging.

**Pull request merged**
